# Настройки Spring MVC
server:
  port: 8081

# Настройки basic.ribbon
#basic:
#  ribbon:
#    eureka:
#      enabled: false
#    NIWSServerListClassName: com.example.additional.config.ConsulServerList
#    ServerListRefreshInterval: 1000

# Настройки Ribbon
#ribbon:
#  client:
#    name: ${RIBBON_NAME:client}

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5342/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    secure-port-enabled: true
